inherit: main

localhost:
  webserver:
    root: 'build'
    proxies: true
    port: 7201
    livereload: true

  manifest:
    resources:
      js:
        - 'src': 'vendor/requirejs/require.js'
          'data-main': 'admin/requireconfig'
      css:
        - 'compiled/admin/vendor/angularBootstrap.css'
        - 'compiled/admin/style.css'
      html: []
      iframe: []

build:
  index: 'external'